export default {
  REQUEST_FIND_USER_BY_ID: 'user/REQUEST_FIND_USER_BY_ID',
  SUCCESS_FIND_USER_BY_ID: 'user/SUCCESS_FIND_USER_BY_ID',
  FAILURE_FIND_USER_BY_ID: 'user/FAILURE_FIND_USER_BY_ID',
  LOGOUT_USER: 'user/LOGOUT_USER',
  REQUEST_CREATE_POST: 'posts/REQUEST_CREATE_POST',
  SUCCESS_CREATE_POST: 'posts/SUCCESS_CREATE_POST',
  FAILURE_CREATE_POST: 'posts/FAILURE_CREATE_POST',
  REQUEST_FIND_POSTS: 'posts/REQUEST_FIND_POSTS',
  SUCCESS_FIND_POSTS: 'posts/SUCCESS_FIND_POSTS',
  FAILURE_FIND_POSTS: 'posts/FAILURE_FIND_POSTS',
};
