export default {
  REQUEST_FETCH_USERS: 'users/REQUEST_FETCH_USERS',
  SUCCESS_FETCH_USERS: 'users/SUCCESS_FETCH_USERS',
  FAILURE_FETCH_USERS: 'users/FAILURE_FETCH_USERS',
  REQUEST_CREATE_USER: 'users/REQUEST_CREATE_USER',
  SUCCESS_CREATE_USER: 'users/SUCCESS_CREATE_USER',
  FAILURE_CREATE_USER: 'users/FAILURE_CREATE_USER',
};