export default {
  REQUEST_FIND_USER_BY_ID: 'app/user/REQUEST_FIND_USER_BY_ID',
  SUCCESS_FIND_USER_BY_ID: 'app/user/SUCCESS_FIND_USER_BY_ID',
  FAILURE_FIND_USER_BY_ID: 'app/user/FAILURE_FIND_USER_BY_ID',
  LOGOUT_USER: 'app/LOGOUT_USER',
  REQUEST_CREATE_POST: 'app/posts/REQUEST_CREATE_POST',
  SUCCESS_CREATE_POST: 'app/posts/SUCCESS_CREATE_POST',
  FAILURE_CREATE_POST: 'app/posts/FAILURE_CREATE_POST',
  REQUEST_FIND_POSTS: 'app/posts/REQUEST_FIND_POSTS',
  SUCCESS_FIND_POSTS: 'app/posts/SUCCESS_FIND_POSTS',
  FAILURE_FIND_POSTS: 'app/posts/FAILURE_FIND_POSTS',
};
